name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Say Hello
      run: echo "Hello, GitHub!"
    - name: Run make
      run: | 
        make
        cd test
        python test.py
